-
  name:  'Frontend/RootDocument'
  uriPattern: 'stencil.grinder/document{node}'
  defaults:
    '@package':    'Sitegeist.Stencil.Grinder'
    '@subpackage': 'Application'
    '@controller': 'Grinder'
    '@action':     'document'
  routeParts:
    'node':
      handler:     'Neos\Neos\Routing\FrontendNodeRoutePartHandlerInterface'
      options:
        onlyMatchSiteNodes: true
  appendExceedingArguments: true

-
  name:  'Frontend/Document'
  uriPattern: 'stencil.grinder/document/{node}'
  defaults:
    '@package':    'Sitegeist.Stencil.Grinder'
    '@subpackage': 'Application'
    '@controller': 'Grinder'
    '@action':     'document'
  routeParts:
    'node':
      handler:     'Neos\Neos\Routing\FrontendNodeRoutePartHandlerInterface'
  appendExceedingArguments: true
